let produtosBD=[],lojaSelecionada='todas',token=localStorage.getItem('ondetem_token')||'',API='http://localhost:3000/api';
function escaparHTML(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
async function api(p,o={}){let h={'Content-Type':'application/json',...(o.headers||{})};if(token)h.Authorization=`Bearer ${token}`;let r=await fetch(API+p,{...o,headers:h}),d=await r.json().catch(()=>({success:false,message:'Resposta inválida'}));if(r.status===401){token='';localStorage.removeItem('ondetem_token')}if(!r.ok)throw Error(d.message||`HTTP ${r.status}`);return d}
document.addEventListener('DOMContentLoaded',async()=>{let t=new URLSearchParams(location.search).get('token');if(t){token=t;localStorage.setItem('ondetem_token',t);history.replaceState({},'',location.pathname)}await buscarProdutosDoBanco();if(token)await atualizarSessao()});
async function buscarProdutosDoBanco(){try{let q=encodeURIComponent(document.getElementById('searchInput')?.value.trim()||''),d=await api(q?`/produtos?q=${q}`:'/produtos');produtosBD=d.data||[];carregarProdutos(produtosBD)}catch(e){let g=document.getElementById('productsGrid');if(g)g.innerHTML='<p>Erro ao carregar dados do servidor. Inicie o backend.</p>'}}
function imgFallback(n){return `data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" width="500" height="300"><rect width="100%" height="100%" fill="%23f4f4f5"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" font-family="Arial" font-size="24" fill="%23666">${encodeURIComponent(String(n).slice(0,22))}</text></svg>`}
function carregarProdutos(l){let g=document.getElementById('productsGrid'),b=document.getElementById('productCount');if(!g)return;g.innerHTML='';if(b)b.textContent=`${l.length} ${l.length===1?'produto':'produtos'}`;if(!l.length){g.innerHTML='<p>Nenhum produto encontrado.</p>';return}l.forEach(p=>{let c=document.createElement('div');c.className='product-card';c.onclick=()=>acaoBloqueada(`visualizar ${p.nome}`);let pr=Number(p.preco);c.innerHTML=`<div class="product-img-wrapper"><img src="${escaparHTML(p.imagem||imgFallback(p.nome))}" alt="${escaparHTML(p.nome)}" loading="lazy"></div><div class="product-info"><h4>${escaparHTML(p.nome)}</h4><p class="product-category">${escaparHTML(p.descricao||p.categoria||'')}</p><p class="product-price">R$ ${pr.toLocaleString('pt-BR',{minimumFractionDigits:2})}</p></div><span class="store-name">🏬 ${escaparHTML(p.loja||'')}</span>`;g.appendChild(c)})}
function aplicarFiltros(){let t=(document.getElementById('searchInput')?.value||'').toLowerCase().trim();carregarProdutos(produtosBD.filter(p=>(!t||[p.nome,p.descricao,p.loja,p.categoria].some(x=>String(x||'').toLowerCase().includes(t)))&&(lojaSelecionada==='todas'||p.loja===lojaSelecionada)))}
function filtrarProdutos(){aplicarFiltros()} function filtrarLoja(l,b){document.querySelectorAll('.store-tags .tag').forEach(x=>x.classList.remove('active'));b?.classList.add('active');lojaSelecionada=l;aplicarFiltros()}
function abrirTelaLogin(){document.getElementById('loginView')?.classList.add('active');document.body.style.overflow='hidden'}function fecharTelaLogin(){document.getElementById('loginView')?.classList.remove('active');document.body.style.overflow='auto'}
async function realizarLogin(e){e.preventDefault();let email=document.getElementById('email')?.value.trim(),senha=prompt('Digite sua senha:');if(!email||!senha)return;try{let d=await api('/auth/login',{method:'POST',body:JSON.stringify({email,senha})});token=d.data.token;localStorage.setItem('ondetem_token',token);fecharTelaLogin();await atualizarSessao();alert(`Bem-vindo, ${d.data.usuario.nome}!`)}catch(x){alert(x.message)}}
async function autenticarGoogle(){try{let r=await fetch(API+'/auth/google');if(r.status===503){alert((await r.json()).message);return}location.href=API+'/auth/google'}catch{alert('Backend indisponível.')}}
async function atualizarSessao(){try{let d=await api('/auth/me');window.ondetemUser=d.data;criarBarraUsuario(d.data);if(['ADMIN','OPERADOR'].includes(d.data.perfil))criarPainelAdmin()}catch{}}
function criarBarraUsuario(u){if(document.getElementById('ot-user'))return;let x=document.createElement('div');x.id='ot-user';Object.assign(x.style,{position:'fixed',bottom:'15px',left:'15px',zIndex:9998,background:'#fff',padding:'10px 14px',borderRadius:'10px',boxShadow:'0 3px 16px #0002',fontFamily:'Arial'});x.innerHTML=`<b>${escaparHTML(u.nome)}</b> · ${u.perfil} <button id="ot-out">Sair</button>`;document.body.appendChild(x);document.getElementById('ot-out').onclick=logout}
async function logout(){try{await api('/auth/logout',{method:'POST'})}catch{}token='';localStorage.removeItem('ondetem_token');document.getElementById('ot-user')?.remove();document.getElementById('ot-admin')?.remove();alert('Sessão encerrada.')}
function acaoBloqueada(a){if(token)return alert('Você está conectado. '+a);alert('Entre para continuar.');abrirTelaLogin()}
async function criarPainelAdmin(){if(document.getElementById('ot-admin'))return;let p=document.createElement('section');p.id='ot-admin';Object.assign(p.style,{position:'fixed',top:'12px',right:'12px',width:'min(94vw,540px)',maxHeight:'90vh',overflow:'auto',zIndex:9997,background:'#fff',padding:'18px',borderRadius:'14px',boxShadow:'0 8px 30px #0003',fontFamily:'Arial'});p.innerHTML=`<h2>Painel OndeTem</h2><div id="ot-stats">...</div><hr><h3>Novo produto</h3><form id="ot-form"><input name="nome" placeholder="Nome" required style="width:100%;padding:7px;margin:3px 0"><input name="descricao" placeholder="Descrição" style="width:100%;padding:7px;margin:3px 0"><input name="preco" type="number" step=".01" min="0" placeholder="Preço" required style="width:100%;padding:7px;margin:3px 0"><input name="estoque" type="number" min="0" placeholder="Estoque" required style="width:100%;padding:7px;margin:3px 0"><select name="loja_id" id="ot-lojas" style="width:100%;padding:7px;margin:3px 0"></select><select name="categoria_id" id="ot-cats" style="width:100%;padding:7px;margin:3px 0"></select><input name="imagem" placeholder="URL da imagem (opcional)" style="width:100%;padding:7px;margin:3px 0"><label><input name="destaque" type="checkbox"> Destaque</label><button>Adicionar</button></form><hr><div id="ot-products">...</div><button onclick="document.getElementById('ot-admin')?.remove()">Fechar painel</button>`;document.body.appendChild(p);await adminDados();document.getElementById('ot-form').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target);try{await api('/admin/produtos',{method:'POST',body:JSON.stringify({nome:f.get('nome'),descricao:f.get('descricao'),preco:Number(f.get('preco')),estoque:Number(f.get('estoque')),loja_id:Number(f.get('loja_id')),categoria_id:Number(f.get('categoria_id')),imagem:f.get('imagem')||'',destaque:f.get('destaque')==='on'})});e.target.reset();await buscarProdutosDoBanco();await adminDados();alert('Produto adicionado.')}catch(x){alert(x.message)}}}
async function adminDados(){let [d,l,c,p]=await Promise.all([api('/admin/dashboard'),api('/lojas'),api('/categorias'),api('/produtos?todos=1')]);document.getElementById('ot-stats').innerHTML=Object.entries(d.data).map(([k,v])=>`<b>${k}:</b> ${v}`).join(' · ');document.getElementById('ot-lojas').innerHTML=l.data.map(x=>`<option value="${x.id}">${escaparHTML(x.nome)}</option>`).join('');document.getElementById('ot-cats').innerHTML=c.data.map(x=>`<option value="${x.id}">${escaparHTML(x.nome)}</option>`).join('');document.getElementById('ot-products').innerHTML='<h3>Produtos</h3>'+p.data.slice(0,100).map(x=>`<div style="padding:7px;border-bottom:1px solid #ddd"><b>${escaparHTML(x.nome)}</b> · R$ ${Number(x.preco).toFixed(2)} · ${escaparHTML(x.loja)} <button onclick="alterarStatus(${x.id},'${x.status==='ATIVO'?'INATIVO':'ATIVO'}')">${x.status==='ATIVO'?'Desativar':'Ativar'}</button>${window.ondetemUser?.perfil==='ADMIN'?` <button onclick="excluirProdutoSeguro(${x.id})">Excluir</button>`:''}</div>`).join('')}
async function alterarStatus(id,status){try{await api(`/admin/produtos/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});await buscarProdutosDoBanco();await adminDados()}catch(e){alert(e.message)}}
async function excluirProdutoSeguro(id){let p=prompt('Digite EXCLUIR + nome exato do produto.');if(p===null)return;try{await api(`/admin/produtos/${id}/exclusao-confirmar`,{method:'POST',body:JSON.stringify({confirmacao:p})});await buscarProdutosDoBanco();await adminDados();alert('Produto excluído.')}catch(e){alert(e.message)}}
Object.assign(window,{buscarProdutosDoBanco,carregarProdutos,filtrarProdutos,filtrarLoja,acaoBloqueada,abrirTelaLogin,fecharTelaLogin,realizarLogin,autenticarGoogle,alterarStatus,excluirProdutoSeguro});
