import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import crypto from 'node:crypto';
import {z} from 'zod';
import {getDb,saveDb} from './config/database.js';
import {hashPassword,verifyPassword,tokenHash,newToken} from './utils/security.js';
import {createAuth,requireRoles} from './middleware/auth.js';

const app=express(),PORT=Number(process.env.PORT||3000),ORIGIN=process.env.FRONTEND_ORIGIN||'http://localhost:5173',DAYS=Math.max(1,Number(process.env.SESSION_DAYS||7));
app.disable('x-powered-by');app.use(helmet());app.use(cors({origin:(o,cb)=>(!o||o===ORIGIN)?cb(null,true):cb(new Error('CORS')) ,credentials:true}));
app.use(express.json({limit:'256kb'}));
app.use('/api',rateLimit({windowMs:900000,limit:180,standardHeaders:'draft-8',legacyHeaders:false}));
const db=await getDb(),auth=createAuth(db);
const rows=(sql,p=[])=>{const r=db.exec(sql,p);if(!r.length)return[];return r[0].values.map(v=>Object.fromEntries(r[0].columns.map((c,i)=>[c,v[i]])))};
const run=(sql,p=[])=>{const s=db.prepare(sql);s.bind(p);s.step();s.free()};
const audit=(req,a,e,id,d={})=>run(`INSERT INTO auditoria(usuario_id,acao,entidade,entidade_id,detalhes,ip) VALUES(?,?,?,?,?,?)`,[req.user?.id??null,a,e,id,JSON.stringify(d),req.ip]);
const products=(extra='',p=[])=>rows(`SELECT p.*,l.nome loja,l.cidade,l.estado,c.nome categoria,COALESCE((SELECT url FROM produto_imagens pi WHERE pi.produto_id=p.id AND pi.principal=1 LIMIT 1),'') imagem FROM produtos p JOIN lojas l ON l.id=p.loja_id JOIN categorias c ON c.id=p.categoria_id WHERE 1=1 ${extra} ORDER BY p.destaque DESC,p.nome COLLATE NOCASE`,p);
const email=z.string().trim().email().max(160).transform(x=>x.toLowerCase()),pass=z.string().min(8).max(128);
const prod=z.object({nome:z.string().trim().min(2).max(150),descricao:z.string().max(500).optional().default(''),preco:z.number().finite().min(0),estoque:z.number().int().min(0).max(100000),loja_id:z.number().int().positive(),categoria_id:z.number().int().positive(),destaque:z.boolean().optional().default(false),imagem:z.string().max(1000).optional().default('')});
const parsed=(s,b)=>{const x=s.safeParse(b);return x.success?x.data:null};

app.get('/api/health',(q,s)=>s.json({success:true,data:{status:'online',version:'6.0.0'}}));
app.get('/api/lojas',(q,s)=>s.json({success:true,data:rows('SELECT * FROM lojas WHERE ativo=1 ORDER BY nome')}));
app.get('/api/categorias',(q,s)=>s.json({success:true,data:rows('SELECT * FROM categorias WHERE ativo=1 ORDER BY nome')}));
app.get('/api/produtos',(q,s)=>{let w=q.query.todos==='1'?'':" AND p.status='ATIVO'",p=[],x=String(q.query.q||'').trim().slice(0,100),l=String(q.query.loja||'').trim(),c=String(q.query.categoria||'').trim();if(x){w+=" AND(p.nome LIKE ? OR p.descricao LIKE ? OR l.nome LIKE ?)";p.push(`%${x}%`,`%${x}%`,`%${x}%`)}if(l){w+=' AND l.nome=?';p.push(l)}if(c){w+=' AND c.nome=?';p.push(c)}s.json({success:true,data:products(w,p)})});

app.post('/api/auth/register',rateLimit({windowMs:900000,limit:20}), (q,s)=>{const b=parsed(z.object({nome:z.string().trim().min(2).max(100),email,senha:pass}),q.body);if(!b)return s.status(400).json({success:false,message:'Dados de cadastro inválidos.'});if(rows('SELECT id FROM usuarios WHERE email=?',[b.email]).length)return s.status(409).json({success:false,message:'E-mail já cadastrado.'});run('INSERT INTO usuarios(nome,email,senha_hash) VALUES(?,?,?)',[b.nome,b.email,hashPassword(b.senha)]);saveDb();s.status(201).json({success:true,message:'Conta criada.'})});
app.post('/api/auth/login',rateLimit({windowMs:900000,limit:30}), (q,s)=>{const e=email.safeParse(q.body?.email),p=pass.safeParse(q.body?.senha);if(!e.success||!p.success)return s.status(400).json({success:false,message:'E-mail e senha são obrigatórios.'});const u=rows('SELECT * FROM usuarios WHERE email=?',[e.data])[0];if(!u||!u.ativo||!verifyPassword(p.data,u.senha_hash))return s.status(401).json({success:false,message:'E-mail ou senha incorretos.'});const t=newToken(),exp=new Date(Date.now()+DAYS*86400000).toISOString();run('INSERT INTO sessoes(usuario_id,token_hash,expira_em,ip,user_agent) VALUES(?,?,?,?,?)',[u.id,tokenHash(t),exp,q.ip,String(q.get('user-agent')||'').slice(0,500)]);audit({user:{id:u.id},ip:q.ip},'LOGIN','USUARIO',u.id);saveDb();s.json({success:true,data:{token:t,expira_em:exp,usuario:{id:u.id,nome:u.nome,email:u.email,perfil:u.perfil}}})});
app.post('/api/auth/logout',auth,(q,s)=>{run('UPDATE sessoes SET revogado_em=CURRENT_TIMESTAMP WHERE id=?',[q.user.sessaoId]);audit(q,'LOGOUT','USUARIO',q.user.id);saveDb();s.json({success:true})});
app.get('/api/auth/me',auth,(q,s)=>s.json({success:true,data:q.user}));

app.get('/api/auth/google',(q,s)=>{if(!process.env.GOOGLE_CLIENT_ID||!process.env.GOOGLE_REDIRECT_URI)return s.status(503).json({success:false,message:'Configure GOOGLE_CLIENT_ID e GOOGLE_REDIRECT_URI no .env para ativar o Google.'});const p=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,redirect_uri:process.env.GOOGLE_REDIRECT_URI,response_type:'code',scope:'openid email profile',access_type:'offline'});s.redirect('https://accounts.google.com/o/oauth2/v2/auth?'+p)});
app.get('/api/auth/google/callback',async(q,s)=>{if(!process.env.GOOGLE_CLIENT_ID||!process.env.GOOGLE_CLIENT_SECRET||!process.env.GOOGLE_REDIRECT_URI)return s.status(503).send('Google OAuth não configurado.');try{const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code:String(q.query.code||''),client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET,redirect_uri:process.env.GOOGLE_REDIRECT_URI,grant_type:'authorization_code'})}),t=await r.json();if(!t.id_token)return s.status(401).send('Falha no Google.');const p=JSON.parse(Buffer.from(t.id_token.split('.')[1],'base64url').toString()),em=String(p.email||'').toLowerCase();if(!em)return s.status(400).send('Google não retornou e-mail.');let u=rows('SELECT * FROM usuarios WHERE email=?',[em])[0];if(!u){run('INSERT INTO usuarios(nome,email,senha_hash) VALUES(?,?,?)',[String(p.name||em).slice(0,100),em,hashPassword(crypto.randomBytes(24).toString('hex'))]);u=rows('SELECT * FROM usuarios WHERE email=?',[em])[0]}const tok=newToken(),exp=new Date(Date.now()+DAYS*86400000).toISOString();run('INSERT INTO sessoes(usuario_id,token_hash,expira_em) VALUES(?,?,?)',[u.id,tokenHash(tok),exp]);saveDb();s.redirect(`${ORIGIN}/?token=${encodeURIComponent(tok)}`)}catch(e){s.status(500).send('Erro no Google OAuth.')}});

app.get('/api/admin/dashboard',auth,requireRoles('ADMIN','OPERADOR'),(q,s)=>s.json({success:true,data:{usuarios:rows('SELECT COUNT(*) c FROM usuarios')[0].c,lojas:rows('SELECT COUNT(*) c FROM lojas WHERE ativo=1')[0].c,categorias:rows('SELECT COUNT(*) c FROM categorias WHERE ativo=1')[0].c,produtos:rows('SELECT COUNT(*) c FROM produtos')[0].c,ativos:rows("SELECT COUNT(*) c FROM produtos WHERE status='ATIVO'")[0].c,auditoria:rows('SELECT COUNT(*) c FROM auditoria')[0].c}}));
app.get('/api/admin/auditoria',auth,requireRoles('ADMIN'),(q,s)=>s.json({success:true,data:rows('SELECT a.*,u.email FROM auditoria a LEFT JOIN usuarios u ON u.id=a.usuario_id ORDER BY a.id DESC LIMIT 200')}));
app.get('/api/admin/usuarios',auth,requireRoles('ADMIN'),(q,s)=>s.json({success:true,data:rows('SELECT id,nome,email,perfil,ativo,criado_em FROM usuarios ORDER BY id DESC')}));
app.post('/api/admin/produtos',auth,requireRoles('ADMIN','OPERADOR'),(q,s)=>{const b=parsed(prod,q.body);if(!b)return s.status(400).json({success:false,message:'Produto inválido.'});if(!rows('SELECT id FROM lojas WHERE id=? AND ativo=1',[b.loja_id]).length||!rows('SELECT id FROM categorias WHERE id=? AND ativo=1',[b.categoria_id]).length)return s.status(400).json({success:false,message:'Loja/categoria inválida.'});run('INSERT INTO produtos(loja_id,categoria_id,nome,descricao,preco,estoque,destaque) VALUES(?,?,?,?,?,?,?)',[b.loja_id,b.categoria_id,b.nome,b.descricao,b.preco,b.estoque,b.destaque?1:0]);const id=rows('SELECT last_insert_rowid() id')[0].id;if(b.imagem)run('INSERT INTO produto_imagens(produto_id,url,alt_text,principal) VALUES(?,?,?,1)',[id,b.imagem,b.nome]);audit(q,'CRIAR','PRODUTO',id,{nome:b.nome});saveDb();s.status(201).json({success:true,data:products(' AND p.id=?',[id])[0]})});
app.patch('/api/admin/produtos/:id',auth,requireRoles('ADMIN','OPERADOR'),(q,s)=>{const id=Number(q.params.id),b=parsed(prod,q.body);if(!Number.isInteger(id)||!b)return s.status(400).json({success:false,message:'Dados inválidos.'});if(!rows('SELECT id FROM produtos WHERE id=?',[id]).length)return s.status(404).json({success:false,message:'Não encontrado.'});run('UPDATE produtos SET loja_id=?,categoria_id=?,nome=?,descricao=?,preco=?,estoque=?,destaque=?,atualizado_em=CURRENT_TIMESTAMP WHERE id=?',[b.loja_id,b.categoria_id,b.nome,b.descricao,b.preco,b.estoque,b.destaque?1:0,id]);if(b.imagem){run('DELETE FROM produto_imagens WHERE produto_id=?',[id]);run('INSERT INTO produto_imagens(produto_id,url,alt_text,principal) VALUES(?,?,?,1)',[id,b.imagem,b.nome])}audit(q,'EDITAR','PRODUTO',id,{nome:b.nome});saveDb();s.json({success:true,data:products(' AND p.id=?',[id])[0]})});
app.patch('/api/admin/produtos/:id/status',auth,requireRoles('ADMIN','OPERADOR'),(q,s)=>{const id=Number(q.params.id),st=q.body?.status;if(!['ATIVO','INATIVO'].includes(st))return s.status(400).json({success:false,message:'Status inválido.'});run('UPDATE produtos SET status=?,atualizado_em=CURRENT_TIMESTAMP WHERE id=?',[st,id]);audit(q,'ALTERAR_STATUS','PRODUTO',id,{status:st});saveDb();s.json({success:true,data:products(' AND p.id=?',[id])[0]})});
app.post('/api/admin/produtos/:id/exclusao-confirmar',auth,requireRoles('ADMIN'),(q,s)=>{const id=Number(q.params.id),p=rows('SELECT id,nome FROM produtos WHERE id=?',[id])[0];if(!p)return s.status(404).json({success:false,message:'Não encontrado.'});if(String(q.body?.confirmacao||'')!==`EXCLUIR ${p.nome}`)return s.status(400).json({success:false,message:`Digite exatamente: EXCLUIR ${p.nome}`});run('DELETE FROM produtos WHERE id=?',[id]);audit(q,'EXCLUIR','PRODUTO',id,{nome:p.nome,confirmado:true});saveDb();s.json({success:true,message:'Excluído.'})});
app.post('/api/admin/lojas',auth,requireRoles('ADMIN'),(q,s)=>{const n=String(q.body?.nome||'').trim();if(n.length<2)return s.status(400).json({success:false,message:'Nome inválido.'});try{run('INSERT INTO lojas(nome,endereco,cidade,estado) VALUES(?,?,?,?)',[n,String(q.body?.endereco||''),String(q.body?.cidade||''),'MT']);saveDb();s.status(201).json({success:true})}catch{s.status(409).json({success:false,message:'Loja já existe.'})}});
app.post('/api/admin/categorias',auth,requireRoles('ADMIN'),(q,s)=>{const n=String(q.body?.nome||'').trim();if(n.length<2)return s.status(400).json({success:false,message:'Nome inválido.'});try{run('INSERT INTO categorias(nome) VALUES(?)',[n]);saveDb();s.status(201).json({success:true})}catch{s.status(409).json({success:false,message:'Categoria já existe.'})}});

app.use('/api',(q,s)=>s.status(404).json({success:false,message:'Rota não encontrada.'}));
app.use((e,q,s,n)=>{console.error(e);s.status(500).json({success:false,message:'Erro interno do servidor.'})});
app.listen(PORT,()=>console.log(`OndeTem API: http://localhost:${PORT}`));
